version: 2.0
shared: &shared
    steps:
      - checkout
      - run:
          name: Bundle gems
          command: |
            echo '--no-rdoc --no-ri' > '.gemrc'
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rspec --format documentation --color --format progress spec

jobs:
  "ruby-2.4":
    <<: *shared
    docker:
      - image: circleci/ruby:2.4

  "ruby-2.5":
    <<: *shared
    docker:
      - image: circleci/ruby:2.5

  "ruby-2.6":
    <<: *shared
    docker:
      - image: circleci/ruby:2.6
        environment:
          REPORT_COVERAGE: 'true'

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.4"
      - "ruby-2.5"
      - "ruby-2.6"
